# Generated by Django 2.2 on 2020-06-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
